baseURL = "https://8bitof.me/"
languageCode = "en-us"
theme = "sada"

[params]
    title = "Simone Minasola"
    author = "Simone Minasola"
    description_1 = "A"
    description_2 = "byte"
    description_3 = "of me..."
    copyright = ""
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Simone Minasola"
        job_title = "Cloud & Data Engineer"
        photo = "images/profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "www.linkedin.com/in/simoneminasola"
        title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/senter7"
        title = "GitHub"

        [[params.social.list]]
        class = "fas"
        icon = "fa-tasks"
        url = "https://www.credly.com/users/simone-minasola/badges"
        title = "Credly"

        [[params.social.list]]
        class = "fas"
        icon = "fa-id-card"
        url = "https://www.8bitof.me/assets/simone.minasola.vcf"
        title = "VCard"

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Master's degree in Computer Engineering"
        college = "University of Rome, Tor Vergata"
        dates = "In progress"

        [[params.education.list]]
        degree = "Bachelor's degree in Computer Engineering"
        college = "University of Rome, Tor Vergata"
        dates = "2017"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "B1"

        [[params.language.list]]
        language = "Italian"
        level = "Native"

    # Interests section
    [params.hobbies]
        title = "Interests"

        [[params.hobbies.list]]
        interest = "I am very interested in Cloud Computing, in particular in the design of scalable and secure infrastructures.  I am very curious about Serverless Computing, and I am trying to learn more and more about its application methodologies, especially in Big Data problems. I really like working on Big Data, and being able to extract and process information useful for BI unit. I enjoy teaching, and have completed the process of becoming an Amazon Authorized Instructor."

    [params.resume]
        title = "Resume"
        description = "You can download the most updated version of my resume by clicking on the link below."
        url_cv = "https://www.8bitof.me/assets/Curriculum_Vitae.pdf" # Added in html file

    [params.qrcode]
        title="V-Card"
        img="images/vcard-qr.jpg"
        alt_img="Personal V-Card"

    [params.aboutme]
        description = "I am a Cloud/Data Engineer with a knowledge in Big Data and Data Transformation. For some years i have dedicated myself to the study of AWS Cloud Services, and i still use them for personal and work projects. I am a Certified AWS Solution Architect and an AWS Authorized Instructor. I've always been passionate about technology in general, and i'm always looking for opportunities to expand my technical knowledge. I am now involved in the Big Data business unit for Claranet Italy, with the aim of extracting value from the data for our customers."

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experiences"

                [[params.jobs.list]]
                position = "Amazon Authorized Instructor"
                dates = "2021 - *Present*"
        		    link = "https://aws.amazon.com/training/aws-authorized-instructor-program/"
                company = "Amazon Web Services"
                details = "Technical Instructor at Amazon Web Services IT for internal and external customer."

        [[params.jobs.list]]
        position = "Cloud Engineer"
        dates = "2019 - *Present*"
		    link = "https://www.claranet.it/"
        company = "Claranet"
        details = "Design and definition of new Cloud infrastructures according to customer specifications, definition and orchestration of ETL workflows using serverless technologies."

        [[params.jobs.list]]
        position = "Junior Developer"
        dates = "2019 - 2019"
		    link = "http://www.cpsweb.it/"
        company = "C.P.S."
        details = "Requirements analysis and functional analysis, migration from on-premise to Cloud, UAT for critical applications."

    # Certification section
    [params.certifications]
        icon = "fa-tasks"
        title = "Certifications"

        [[params.certifications.list]]
        title = "AWS Authorizer Instructor"
        url = "https://www.credly.com/badges/2f53a51d-2354-432c-b80d-14706aa071b8/public_url"
        acronym = "AAI"

        [[params.certifications.list]]
        title = "HashiCorp Certified: Terraform Associate"
        url = "https://www.credly.com/badges/263c7e34-06f3-454a-a2da-203d476c5aa0/linked_in"
        acronym = "Terraform Associate"

        [[params.certifications.list]]
        title = "AWS Certified Solutions Architect – Associate"
        url = "https://www.credly.com/badges/31f536bd-e38e-472b-a5b3-6d74073e37da/linked_in"
        acronym = "SAA-C02"

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "BD/AI System for ALF Project - Sole24Ore (public case)"
        url = "https://summit-emea.virtual.awsevents.com/media/t/1_1epwdm9o/210385833"
        description = "Intelligent virtual assistant to support financial professionals. I took care of all the data ingestion and automatisms part, I created the infrastructure for the orchestration of the various tasks (ETL jobs, deployment of ML models, testing and dry run, saving in DWH). I have used several technologies, including StepFunction Data Science SDK, Troposphere, CFN, Python, PySpark."

        [[params.projects.list]]
        title = "ETL workflow for massive processing - Confidential"
        description = "ETL workflow build on AWS with StepFunction, lambda, Glue and Apache Spark. I used PySpark, and i wrote the scripts to run both locally and on AWS Glue independently, to have the customer run the unit tests as desired. Finally, a pipeline manages the release in the staging and production environment."

        [[params.projects.list]]
        title = "Recommendation engine - CondéNast International"
        url = "https://www.claranet.co.uk/case-studies/conde-nast-creates-new-user-experience-using-aws-cloud-and-artificial-intelligence" # youtube video: https://youtu.be/O19msbttcdo
        description = "GENIUS is a recommendation engine used by CondéNast International for all of its websites (Vanity Fair, Vogue, GQ, ...). I participated in the realization of a POC for the comparison of recommendation services, creating ETL jobs for data transformation and uploading to Amazon Personalize."

        [[params.projects.list]]
        title = "Contact Center on Cloud (confidential)"
        description = "Simple and powerful Contact Center created for one of the largest European insurance brands on AWS with Amazon Connect. The entire management system has been developed completely serverless with Lambda, Kinesis and Aurora Serverless using Terraform as IaC tool."


    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "IaC (Terraform, CFN, SAM)"
        skillrating = 90 # out of 100

        [[params.skills.list]]
        skill = "ETL, Data Engineering, Databases"
        skillrating = 80

        [[params.skills.list]]
        skill = "AWS CI/CD Tools & DevOps Tools"
        skillrating = 70

        [[params.skills.list]]
        skill = "Scripting & Coding"
        skillrating = 75

        [[params.skills.list]]
        skill = "Teaching"
        skillrating = 85
